apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 35Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sharedfolder"
