apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      book: web
  template:
    metadata:
      labels:
        book: web
    spec:
      containers:
      - name: notebook-site
        image: notebookserver:1.0
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: hostdataclaim
---
apiVersion: v1
kind: Service
metadata:
  name: book-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    book: web
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30001


