apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-local
spec:
  capacity:
    storage: 35Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.122.106
    path: /data
